### ISSUE TITLE
[Server] [Api] Create APIs to Read Posts Templates

### ISSUE THREAD

**Issue by arunselvakumar** [One-12/Client#16]
**As an Application User,**
I need to get all Post Templates.

**Request - Search/Get Post Templates**
**API:** http://localhost:3000/api/posts-templates?offset=1&size=20&query=vadivelu
**Type:** GET
**Header:**
**Provider:** Facebook/ Google
**Access-Token:** Token

**API - Get Popular Post Templates**
**API:** http://localhost:3000/api/posts-templates?offset=1&size=20&page=popular
**Type:** GET
**Header:**
**Provider:** Facebook/ Google
**Access-Token:** Token

**PS:** All the APIs needs to support pagination, 'offset' properties means page number and 'size' means the number of items needed in that page.

**Comment by Prakash-Selvaraj-Ash** [comment]
As an Application User,
I need to get all Post Templates. -- COMPLETED

Request - Search/Get Post Templates
instead this // API: http://localhost:3000/api/posts-templates?offset=1&size=20&query=vadivelu
use this // API: http://localhost:3000/api/posts-templates?offset=1&size=20&tag=vadivelu
Type: GET
Header:
Provider: Facebook/ Google
Access-Token: Token

API - Get Popular Post Templates
API: http://localhost:3000/api/posts-templates?offset=1&size=20&page=popular
Type: GET
Header:
Provider: Facebook/ Google
Access-Token: Token

PS: All the APIs needs to support pagination, 'offset' properties means page number and 'size' means the number of items needed in that page.

**Comment by arunselvakumar** [comment]
Bravo! Bravo!
