### ISSUE TITLE
Only Get Post (Feeds) for the particular User, should return 401 for invalid token

### ISSUE THREAD

**Issue by arunselvakumar** [One-12/Client#18]
Get posts based on category (ie Popular Posts, Fresh Post Getting Posts By Tags) - The service should return 401 only if the token passed is invalid - If the token is not passed, data should be returned irrespective of whether the user is logged in or not.

As proposed, we can create a new capability to get the posts for particular user's following post.

**Comment by Prakash-Selvaraj-Ash** [comment]
GetPosts doesnt require any token and wont validate the user, it will return posts based on the query
query can be 'tag' or 'page'

GetFollowingUserPosts requires a valid token to get the following user posts
