### ISSUE TITLE
User Information not retrieved when getting posts 

### ISSUE THREAD

**Issue by arunselvakumar** [One-12/Client#19]
**Actual Behaviour:**
User Information is not retrieved

**Expected Behaviour:**
User Information should be retrived. 
Here is the expected model from server,
```
export interface PostResponseModel {
  id: string;
  title: string;
  content: string;
  views: number;
  points: number;
  type: string;
  tags: TagModel[];
  postedOn: Date;
  commentsCount: number;
  likesCount: number;
  postedBy: UserModel;
}

interface TagModel {
  id: string;
  name: string;
}

interface UserModel {
  id: string;
  userName: string;
  firstName: string;
  lastName: string;
  middleName: string;
}
```

**Comment by Prakash-Selvaraj-Ash** [comment]
User information sent along with post response, as of now we are not storing first name, last name fields
We will finalize which field are all needed from firebase and then we will persists those information
for now we are storing email, which was sent in post details
