### ISSUE TITLE
[Server] [API] Create an API to Follow User/ Unfollow User

### ISSUE THREAD

**Issue by arunselvakumar** [One-12/Client#5]
**As a Application User,**
I need to follow/unfollow other users
**So that,**
I can get posts from them in my timeline.

Request:
**API**: http://localhost:3000/api/user?action=follow&id={userId}
**Type**: POST
**Header:**
Provider: Facebook/ Google
Access-Token: Token

**API**: http://localhost:3000/api/user?action=unfollow&id={userId}
**Type**: POST
**Header:**
Provider: Facebook/ Google
Access-Token: Token

**Comment by arunselvakumar** [comment]
@Prakash-Selvaraj-Ash 
Token returned from Google Firebase is JWT. _Cheers!_

![image](https://user-images.githubusercontent.com/3615264/81475813-1367af80-922c-11ea-8cc3-316c3ccdccad.png)

**Comment by Prakash-Selvaraj-Ash** [comment]
completed

**Comment by arunselvakumar** [comment]
Nice 👍
