### ISSUE TITLE
[Server] [Api] Create APIs to get Posts

### ISSUE THREAD

**Issue by arunselvakumar** [One-12/Client#6]
**As a Application User,**
I need to see posts.

**Request - Get Posts for Tags**
**API**: http://localhost:3000/api/posts?tag=corona&offset=1&size=20
**Type**: GET
**Header:**
Provider: Facebook/ Google
Access-Token: Token

**Request - Get Fresh Posts**
**API**: http://localhost:3000/api/posts?page=fresh&offset=1&size=20
**Type**: GET
**Header:**
Provider: Facebook/ Google
Access-Token: Token

**Request - Get Posts from Users I follow**
**API**: http://localhost:3000/api/posts?offset=1&size=20
**Type**: GET
**Header:**
Provider: Facebook/ Google
Access-Token: Token

**Request - Get Posts from Editor Picks**
**API**: http://localhost:3000/api/posts?page=editor-picks&offset=1&size=20
**Type**: GET
**Header:**
Provider: Facebook/ Google
Access-Token: Token

**Request - Get Trending Posts**
**API**: http://localhost:3000/api/posts?page=trending&offset=1&size=20
**Type**: GET
**Header:**
Provider: Facebook/ Google
Access-Token: Token

PS: All the APIs needs to support pagination, '_offset_' properties means page number and '_size_' means the number of items needed in that page.

**Comment by arunselvakumar** [comment]
We can close this?

**Comment by Prakash-Selvaraj-Ash** [comment]
completed
